import { SUPPORTED_LOCALES } from './locale';

/** UI-Texte für Website-Chrome (Header, Footer, gemeinsame Labels) */
export const UI_STRINGS = {
  de: {
    profile: 'Profil',
    login: 'Anmelden',
    logout: 'Abmelden',
    admin: 'Admin',
    language: 'Sprache',
    guideLanguage: 'Guide-Sprache',
    guideLanguageHint: 'Website',
    guideLanguageReset: 'Standard',
    impressum: 'Impressum',
    privacy: 'Datenschutz (DSGVO)',
    fairUseNote:
      'Cover, Logos und Spieltitel dienen nur der Identifikation im redaktionellen Datenbank-Kontext. TrophyBase ist nicht mit den Rechteinhabern affiliated.',
    consentTitle: 'Hinweise zu externen Inhalten',
    consentBody:
      'Kein Tracking, keine Affiliate-Cookies. YouTube-Videos laden wir erst nach deiner Zustimmung (Cookies von Google). Vorschaubilder kommen vom YouTube-Bild-CDN, ohne Player.',
    consentAllowYoutube: 'YouTube erlauben',
    consentNecessary: 'Ablehnen',
    consentYoutubeGate:
      'Vorschaubild ohne Player. YouTube setzt Cookies von Google erst, wenn du das Video lädst.',
    consentYoutubeLoad: 'YouTube-Video laden',
    dbConnected: 'Erfolgreich verbunden!',
    dbFailed: 'Fehlgeschlagen',
    dbLabel: 'DB',
    backDashboard: '← Zurück zum Dashboard',
    trophies: 'Trophäen',
    fullGameplay: 'Walkthrough',
    completion: 'Sammelobjekte',
    bosses: 'Bosse',
    hideCompleted: 'Erledigte ausblenden',
    guideNotFoundTitle: 'Guide nicht gefunden',
    guideNotFoundBody:
      'Zu diesem Link gibt es gerade kein Spiel. Vielleicht ist der Link veraltet oder der Guide wird noch überarbeitet.',
    guideTabs: 'Guide-Bereiche',
    prevTab: 'Vorheriger Bereich',
    nextTab: 'Nächster Bereich',
    guideLoading: 'Guide-Daten werden geladen …',
    loadingGuide: 'Guide wird geladen…',
    searchPlaceholder: 'Spieltitel, Genre oder Studio …',
    advancedSearch: 'Erweiterte Suche',
    advancedSearchHint:
      'Kombiniere Spieltitel, Studio, Genre und Konsole. Leere Felder werden ignoriert.',
    searchTitle: 'Spieltitel',
    searchDeveloper: 'Studio',
    studioLabel: 'Studio',
    publisherLabel: 'Publisher',
    searchGenre: 'Genre',
    searchConsole: 'Konsole',
    searchSubmit: 'Suchen',
    searchReset: 'Zurücksetzen',
    searchBack: '← Zurück zur Startseite',
    consoleAll: 'Alle Konsolen',
    advancedSearchEmpty: 'Bitte mindestens ein Feld ausfüllen.',
    searchAria: 'Spielsuche',
    searchStartAria: 'Suche starten',
    searchResults: 'Suchergebnisse',
    searchLoading: 'Suche läuft…',
    searchNoResults: 'Keine passenden Einträge in der Datenbank gefunden.',
    searchPrevPage: 'Vorherige Seite',
    searchNextPage: 'Nächste Seite',
    searchPageStatus: 'Seite {page} von {total}',
    backToSearch: '← Zurück zur Suche',
    breadcrumbNav: 'Brotkrumen',
    breadcrumbHome: 'Startseite',
    moreFromCreator: 'Weitere Guides von {name}',
    moreFromCreators: 'Weitere Guides der Creator',
    similarGuides: 'Ähnliche Guides',
    homeKicker: 'TrophyBase · Dein Guide-Hub',
    homeTitle: 'Finde deinen nächsten Platin-Run',
    homeSub:
      'Kuratierte Reihen – vom Souls-Hardcore bis zur Familien-Platin. Wähle die Reihe, die zu deinem Gamer-Typ passt.',
    watchlistTitle: 'Watchlist',
    watchlistCountOne: '1 Spiel',
    watchlistCountMany: '{n} Spiele',
    watchlistEmpty:
      'Noch keine Spiele auf deiner Watchlist. Markiere Spiele mit dem ☆-Symbol in den Kategorien oder auf der Spieleseite.',
    creatorCredit:
      'Dieser Guide nutzt Inhalte aus den wunderbaren Videos von {name}. Wenn du die Videos von {name} genauso zu schätzen weißt wie wir, lass doch bitte ein Abo da. Jede Unterstützung hilft, um noch mehr tolle Inhalte zu erstellen!',
    creatorYoutube: 'YouTube',
  },
  en: {
    profile: 'Profile',
    login: 'Sign in',
    logout: 'Sign out',
    admin: 'Admin',
    language: 'Language',
    guideLanguage: 'Guide language',
    guideLanguageHint: 'Site',
    guideLanguageReset: 'Default',
    impressum: 'Legal notice',
    privacy: 'Privacy (GDPR)',
    fairUseNote:
      'Covers, logos and titles are used only to identify games in an editorial database. TrophyBase is not affiliated with the rights holders.',
    consentTitle: 'External content',
    consentBody:
      'No tracking and no affiliate cookies. YouTube videos load only after you consent (Google cookies). Preview images come from YouTube’s image CDN, without the player.',
    consentAllowYoutube: 'Allow YouTube',
    consentNecessary: 'Decline',
    consentYoutubeGate:
      'Preview image without the player. YouTube sets Google cookies only when you load the video.',
    consentYoutubeLoad: 'Load YouTube video',
    dbConnected: 'Connected successfully!',
    dbFailed: 'Failed',
    dbLabel: 'DB',
    backDashboard: '← Back to dashboard',
    trophies: 'Trophies',
    fullGameplay: 'Walkthrough',
    completion: 'Collectibles',
    bosses: 'Bosses',
    hideCompleted: 'Hide completed',
    guideNotFoundTitle: 'Guide not found',
    guideNotFoundBody:
      'There is no game behind this link right now. It may be outdated, or the guide is still being reworked.',
    guideTabs: 'Guide sections',
    prevTab: 'Previous section',
    nextTab: 'Next section',
    guideLoading: 'Loading guide data…',
    loadingGuide: 'Loading guide…',
    searchPlaceholder: 'Game title, genre or studio…',
    advancedSearch: 'Advanced search',
    advancedSearchHint:
      'Combine game title, studio, genre and console. Empty fields are ignored.',
    searchTitle: 'Game title',
    searchDeveloper: 'Studio',
    studioLabel: 'Studio',
    publisherLabel: 'Publisher',
    searchGenre: 'Genre',
    searchConsole: 'Console',
    searchSubmit: 'Search',
    searchReset: 'Reset',
    searchBack: '← Back to home',
    consoleAll: 'All consoles',
    advancedSearchEmpty: 'Please fill in at least one field.',
    searchAria: 'Game search',
    searchStartAria: 'Start search',
    searchResults: 'Search results',
    searchLoading: 'Searching…',
    searchNoResults: 'No matching games found in the database.',
    searchPrevPage: 'Previous page',
    searchNextPage: 'Next page',
    searchPageStatus: 'Page {page} of {total}',
    backToSearch: '← Back to search',
    breadcrumbNav: 'Breadcrumb',
    breadcrumbHome: 'Home',
    moreFromCreator: 'More guides by {name}',
    moreFromCreators: 'More guides by these creators',
    similarGuides: 'Similar guides',
    homeKicker: 'TrophyBase · Your guide hub',
    homeTitle: 'Find your next platinum run',
    homeSub:
      'Curated rows — from Souls hardcore to family platinums. Pick the series that fits your play style.',
    watchlistTitle: 'Watchlist',
    watchlistCountOne: '1 game',
    watchlistCountMany: '{n} games',
    watchlistEmpty:
      'No games on your watchlist yet. Star games in the categories or on a game page.',
    creatorCredit:
      'This guide uses footage from the wonderful videos by {name}. If you enjoy {name}’s videos as much as we do, please consider subscribing. Every bit of support helps create even more great content!',
    creatorYoutube: 'YouTube',
  },
  es: {
    profile: 'Perfil',
    login: 'Iniciar sesión',
    logout: 'Cerrar sesión',
    admin: 'Admin',
    language: 'Idioma',
    guideLanguage: 'Idioma de la guía',
    guideLanguageHint: 'Sitio',
    guideLanguageReset: 'Predeterminado',
    impressum: 'Aviso legal',
    privacy: 'Privacidad (RGPD)',
    fairUseNote:
      'Carátulas, logos y títulos se usan solo para identificar juegos en una base editorial. TrophyBase no está afiliado a los titulares.',
    consentTitle: 'Contenido externo',
    consentBody:
      'Sin medición de audiencia ni cookies de afiliados. Los vídeos de YouTube se cargan solo con tu consentimiento (cookies de Google). Las miniaturas vienen del CDN de imágenes de YouTube, sin reproductor.',
    consentAllowYoutube: 'Permitir YouTube',
    consentNecessary: 'Rechazar',
    consentYoutubeGate:
      'Miniatura sin reproductor. YouTube establece cookies de Google solo al cargar el vídeo.',
    consentYoutubeLoad: 'Cargar vídeo de YouTube',
    dbConnected: '¡Conectado correctamente!',
    dbFailed: 'Error',
    dbLabel: 'BD',
    backDashboard: '← Volver al panel',
    trophies: 'Trofeos',
    fullGameplay: 'Walkthrough',
    completion: 'Coleccionables',
    bosses: 'Jefes',
    hideCompleted: 'Ocultar completados',
    guideNotFoundTitle: 'Guía no encontrada',
    guideNotFoundBody:
      'Ahora mismo no hay ningún juego detrás de este enlace. Puede estar obsoleto o la guía aún se está revisando.',
    guideTabs: 'Secciones de la guía',
    prevTab: 'Sección anterior',
    nextTab: 'Sección siguiente',
    guideLoading: 'Cargando datos de la guía…',
    loadingGuide: 'Cargando guía…',
    searchPlaceholder: 'Título, género o estudio…',
    advancedSearch: 'Búsqueda avanzada',
    advancedSearchHint:
      'Combina título, estudio, género y consola. Los campos vacíos se ignoran.',
    searchTitle: 'Título',
    searchDeveloper: 'Estudio',
    studioLabel: 'Estudio',
    publisherLabel: 'Publisher',
    searchGenre: 'Género',
    searchConsole: 'Consola',
    searchSubmit: 'Buscar',
    searchReset: 'Restablecer',
    searchBack: '← Volver al inicio',
    consoleAll: 'Todas las consolas',
    advancedSearchEmpty: 'Rellena al menos un campo.',
    searchAria: 'Búsqueda de juegos',
    searchStartAria: 'Iniciar búsqueda',
    searchResults: 'Resultados de búsqueda',
    searchLoading: 'Buscando…',
    searchNoResults: 'No hay juegos coincidentes en la base de datos.',
    searchPrevPage: 'Página anterior',
    searchNextPage: 'Página siguiente',
    searchPageStatus: 'Página {page} de {total}',
    backToSearch: '← Volver a la búsqueda',
    breadcrumbNav: 'Migas de pan',
    breadcrumbHome: 'Inicio',
    moreFromCreator: 'Más guías de {name}',
    moreFromCreators: 'Más guías de estos creadores',
    similarGuides: 'Guías similares',
    homeKicker: 'TrophyBase · Tu hub de guías',
    homeTitle: 'Encuentra tu próxima platino',
    homeSub:
      'Filas curadas — del hardcore Souls a platino familiar. Elige la saga que encaje contigo.',
    watchlistTitle: 'Watchlist',
    watchlistCountOne: '1 juego',
    watchlistCountMany: '{n} juegos',
    watchlistEmpty:
      'Todavía no hay juegos en tu watchlist. Márcalos con el ☆ en las categorías o en la ficha del juego.',
    creatorCredit:
      'Esta guía utiliza imágenes de los vídeos de {name}. Si te gustan tanto como a nosotros, suscríbete. Cada apoyo ayuda a crear aún más contenido.',
    creatorYoutube: 'YouTube',
  },
};

export const LOCALE_META = {
  ja: { label: '日本語', flag: '🇯🇵', short: 'JA' },
  en: { label: 'English', flag: '🇬🇧', short: 'EN' },
  fr: { label: 'Français', flag: '🇫🇷', short: 'FR' },
  es: { label: 'Español', flag: '🇪🇸', short: 'ES' },
  de: { label: 'Deutsch', flag: '🇩🇪', short: 'DE' },
  it: { label: 'Italiano', flag: '🇮🇹', short: 'IT' },
  nl: { label: 'Nederlands', flag: '🇳🇱', short: 'NL' },
  pt: { label: 'Português', flag: '🇵🇹', short: 'PT' },
  ru: { label: 'Русский', flag: '🇷🇺', short: 'RU' },
  ko: { label: '한국어', flag: '🇰🇷', short: 'KO' },
  'zh-hant': { label: '繁體中文', flag: '🇹🇼', short: 'ZH' },
  'zh-hans': { label: '简体中文', flag: '🇨🇳', short: 'ZH' },
  fi: { label: 'Suomi', flag: '🇫🇮', short: 'FI' },
  sv: { label: 'Svenska', flag: '🇸🇪', short: 'SV' },
};

export function t(locale, key) {
  const loc = UI_STRINGS[locale] ? locale : 'de';
  return UI_STRINGS[loc][key] ?? UI_STRINGS.de[key] ?? UI_STRINGS.en?.[key] ?? key;
}

export function localeOptions(codes = SUPPORTED_LOCALES) {
  return codes
    .filter((code) => LOCALE_META[code])
    .map((code) => ({
      code,
      ...LOCALE_META[code],
    }));
}
