import { SUPPORTED_LOCALES } from './locale';

/** UI-Texte für Website-Chrome (Header, Footer, gemeinsame Labels) */
export const UI_STRINGS = {
  de: {
    profile: 'Profil',
    login: 'Anmelden',
    logout: 'Abmelden',
    admin: 'Admin',
    language: 'Sprache',
    guideLanguage: 'Guide-Sprache',
    guideLanguageHint: 'Website',
    guideLanguageReset: 'Standard',
    impressum: 'Impressum',
    privacy: 'Datenschutz (DSGVO)',
    howTo: 'Kurz erklärt',
    howToLead: 'Ein paar Handgriffe, die die Guides schneller machen.',
    howToSwipeTitle: 'Wischen und Pfeiltasten',
    howToSwipeBody:
      'Im Guide wechselt Wischen nach links den nächsten Reiter, nach rechts den vorherigen. Auf der Tastatur gilt dasselbe mit Pfeil rechts und Pfeil links.',
    howToCheckTitle: 'Abhaken und ausblenden',
    howToCheckBody:
      'Trophäen und Guide-Schritte lassen sich abhaken. „Erledigte ausblenden“ räumt die Liste auf. Im Kopf der Seite blendet Einblenden und Ausblenden Spiele ein, die du schon versteckt hast.',
    howToWatchTitle: 'Watchlist',
    howToWatchBody:
      'Der Stern merkt sich ein Spiel in diesem Browser. Die Liste steht auf der Startseite. Ein Konto braucht es dafür nicht.',
    howToLandscapeTitle: 'Querformat',
    howToLandscapeBody:
      'Mit laufendem Video im Hochformat erscheint ein Hinweis, das Handy zu drehen. Die Schritte und das Bild liegen dann nebeneinander.',
    howToReportTitle: 'Fehler melden',
    howToReportBody:
      'Text im Guide markieren. Darüber erscheint „Fehler melden“. Die Meldung geht an die Redaktion, samt der Stelle, die du markiert hast.',
    hintSwipe: 'Nach links oder rechts wischen wechselt den Reiter.',
    hintWatchlist: 'Der Stern legt das Spiel auf die Watchlist.',
    hintMore: 'Mehr',
    hintOk: 'OK',
    hintLandscape: 'Für die beste Guide-Erfahrung mit Video bitte das Gerät ins Querformat drehen.',
    fairUseNote:
      'Cover, Logos und Spieltitel dienen nur der Identifikation im redaktionellen Datenbank-Kontext. TrophyBase ist nicht mit den Rechteinhabern affiliated.',
    consentTitle: 'Hinweise zu externen Inhalten',
    consentBody:
      'Kein Tracking, keine Affiliate-Cookies. YouTube-Videos laden wir erst nach deiner Zustimmung (Cookies von Google). Vorschaubilder kommen vom YouTube-Bild-CDN, ohne Player.',
    consentAllowYoutube: 'YouTube erlauben',
    consentNecessary: 'Ablehnen',
    consentYoutubeGate:
      'Vorschaubild ohne Player. YouTube setzt Cookies von Google erst, wenn du das Video lädst.',
    consentYoutubeLoad: 'YouTube-Video laden',
    dbConnected: 'Erfolgreich verbunden!',
    dbFailed: 'Fehlgeschlagen',
    dbLabel: 'DB',
    backDashboard: '← Zurück zum Dashboard',
    trophies: 'Trophäen',
    fullGameplay: 'Walkthrough',
    completion: 'Sammelobjekte',
    bosses: 'Bosse',
    hideCompleted: 'Erledigte ausblenden',
    trophyChecklist: 'Trophäen-Checkliste',
    hiddenTrophies: 'Versteckte Trophäen',
    hiddenTrophiesShow: 'Anzeigen',
    hiddenTrophiesHide: 'Verstecken',
    hiddenTrophiesAlways: 'Immer anzeigen',
    hiddenTrophyName: 'Versteckte Trophäe',
    overallProgress: 'Gesamtfortschritt',
    releaseYear: 'Release-Jahr',
    watchlistAdd: 'Zur Watchlist',
    watchlistOn: 'Auf Watchlist',
    watchlistAdded: 'Zur Watchlist hinzugefügt.',
    watchlistRemoved: 'Von Watchlist entfernt.',
    watchlistAddTitle: 'Zur Watchlist hinzufügen',
    watchlistRemoveTitle: 'Von Watchlist entfernen',
    watchlistFailed: 'Watchlist konnte nicht aktualisiert werden.',
    share: 'Teilen',
    shareCopied: 'Link kopiert.',
    shareFailed: 'Link konnte nicht kopiert werden.',
    guideNotFoundTitle: 'Guide nicht gefunden',
    guideNotFoundBody:
      'Zu diesem Link gibt es gerade kein Spiel. Vielleicht ist der Link veraltet oder der Guide wird noch überarbeitet.',
    guideTabs: 'Guide-Bereiche',
    prevTab: 'Vorheriger Bereich',
    nextTab: 'Nächster Bereich',
    guideLoading: 'Guide-Daten werden geladen …',
    loadingGuide: 'Guide wird geladen…',
    searchPlaceholder: 'Spieltitel, Genre oder Studio …',
    advancedSearch: 'Erweiterte Suche',
    advancedSearchHint:
      'Kombiniere Spieltitel, Studio, Genre und Konsole. Leere Felder werden ignoriert.',
    searchTitle: 'Spieltitel',
    searchDeveloper: 'Studio',
    studioLabel: 'Studio',
    publisherLabel: 'Publisher',
    searchGenre: 'Genre',
    searchConsole: 'Konsole',
    searchSubmit: 'Suchen',
    searchReset: 'Zurücksetzen',
    searchBack: '← Zurück zur Startseite',
    consoleAll: 'Alle Konsolen',
    advancedSearchEmpty: 'Bitte mindestens ein Feld ausfüllen.',
    searchAria: 'Spielsuche',
    searchStartAria: 'Suche starten',
    searchResults: 'Suchergebnisse',
    searchLoading: 'Suche läuft…',
    searchNoResults: 'Keine passenden Einträge in der Datenbank gefunden.',
    searchPrevPage: 'Vorherige Seite',
    searchNextPage: 'Nächste Seite',
    searchPageStatus: 'Seite {page} von {total}',
    backToSearch: '← Zurück zur Suche',
    breadcrumbNav: 'Brotkrumen',
    breadcrumbHome: 'Startseite',
    moreFromCreator: 'Weitere Guides von {name}',
    moreFromCreators: 'Weitere Guides der Creator',
    similarGuides: 'Ähnliche Guides',
    homeKicker: 'TrophyBase · Dein Guide-Hub',
    homeTitle: 'Finde deinen nächsten Platin-Run',
    homeSub:
      'Kuratierte Reihen – vom Souls-Hardcore bis zur Familien-Platin. Wähle die Reihe, die zu deinem Gamer-Typ passt.',
    watchlistTitle: 'Watchlist',
    watchlistCountOne: '1 Spiel',
    watchlistCountMany: '{n} Spiele',
    watchlistEmpty:
      'Noch keine Spiele auf deiner Watchlist. Markiere Spiele mit dem ☆-Symbol in den Kategorien oder auf der Spieleseite.',
    creatorCredit:
      'Dieser Guide nutzt Inhalte aus den Videos von {name}. Wenn du die Videos von {name} genauso zu schätzen weißt wie wir, lass doch bitte ein Abo da. Jede Unterstützung hilft, um noch mehr tolle Inhalte zu erstellen!',
    creatorYoutube: 'YouTube',
    platinGuide: 'Platin-Guide',
    gameOverview: 'Überblick zum {title} Platin-Guide',
    trophiesTotal: 'Trophäen gesamt',
    trophiesMissable: 'Verpassbare Trophäen',
    trophiesOnline: 'Online-Trophäen',
    playtimeTitle: 'Spieldauer',
    playtimeStory: 'Nur Hauptstory',
    playtimeComplete: 'Komplettierer',
    playtimeHours: '{n} Std.',
    serverDeadPlatinum: 'Wegen Abschaltung der Server ist die Platin nicht mehr regulär erspielbar.',
  },
  en: {
    profile: 'Profile',
    login: 'Sign in',
    logout: 'Sign out',
    admin: 'Admin',
    language: 'Language',
    guideLanguage: 'Guide language',
    guideLanguageHint: 'Site',
    guideLanguageReset: 'Default',
    impressum: 'Legal notice',
    privacy: 'Privacy (GDPR)',
    howTo: 'How it works',
    howToLead: 'A few gestures that make the guides faster.',
    howToSwipeTitle: 'Swipe and arrow keys',
    howToSwipeBody:
      'In a guide, swipe left for the next section and right for the previous one. On a keyboard, the right and left arrow keys do the same.',
    howToCheckTitle: 'Check off and hide',
    howToCheckBody:
      'Trophies and guide steps can be checked off. “Hide completed” clears the list. Show and hide in the header brings back games you have tucked away.',
    howToWatchTitle: 'Watchlist',
    howToWatchBody:
      'The star keeps a game in this browser. The list sits on the home page. No account is required.',
    howToLandscapeTitle: 'Landscape',
    howToLandscapeBody:
      'With a video playing in portrait, a note asks you to turn the phone. The steps and the picture then sit side by side.',
    howToReportTitle: 'Report an error',
    howToReportBody:
      'Select text in the guide. “Report error” appears above it. The note goes to the editors, with the passage you marked.',
    hintSwipe: 'Swipe left or right to change section.',
    hintWatchlist: 'The star adds this game to your watchlist.',
    hintMore: 'More',
    hintOk: 'OK',
    hintLandscape: 'For the best guide experience with video, turn the device sideways.',
    fairUseNote:
      'Covers, logos and titles are used only to identify games in an editorial database. TrophyBase is not affiliated with the rights holders.',
    consentTitle: 'External content',
    consentBody:
      'No tracking and no affiliate cookies. YouTube videos load only after you consent (Google cookies). Preview images come from YouTube’s image CDN, without the player.',
    consentAllowYoutube: 'Allow YouTube',
    consentNecessary: 'Decline',
    consentYoutubeGate:
      'Preview image without the player. YouTube sets Google cookies only when you load the video.',
    consentYoutubeLoad: 'Load YouTube video',
    dbConnected: 'Connected successfully!',
    dbFailed: 'Failed',
    dbLabel: 'DB',
    backDashboard: '← Back to dashboard',
    trophies: 'Trophies',
    fullGameplay: 'Walkthrough',
    completion: 'Collectibles',
    bosses: 'Bosses',
    hideCompleted: 'Hide completed',
    trophyChecklist: 'Trophy checklist',
    hiddenTrophies: 'Hidden trophies',
    hiddenTrophiesShow: 'Show',
    hiddenTrophiesHide: 'Hide',
    hiddenTrophiesAlways: 'Always show',
    hiddenTrophyName: 'Hidden trophy',
    overallProgress: 'Overall progress',
    releaseYear: 'Release year',
    watchlistAdd: 'Add to watchlist',
    watchlistOn: 'On watchlist',
    watchlistAdded: 'Added to watchlist.',
    watchlistRemoved: 'Removed from watchlist.',
    watchlistAddTitle: 'Add to watchlist',
    watchlistRemoveTitle: 'Remove from watchlist',
    watchlistFailed: 'Could not update the watchlist.',
    share: 'Share',
    shareCopied: 'Link copied.',
    shareFailed: 'Could not copy the link.',
    guideNotFoundTitle: 'Guide not found',
    guideNotFoundBody:
      'There is no game behind this link right now. It may be outdated, or the guide is still being reworked.',
    guideTabs: 'Guide sections',
    prevTab: 'Previous section',
    nextTab: 'Next section',
    guideLoading: 'Loading guide data…',
    loadingGuide: 'Loading guide…',
    searchPlaceholder: 'Game title, genre or studio…',
    advancedSearch: 'Advanced search',
    advancedSearchHint:
      'Combine game title, studio, genre and console. Empty fields are ignored.',
    searchTitle: 'Game title',
    searchDeveloper: 'Studio',
    studioLabel: 'Studio',
    publisherLabel: 'Publisher',
    searchGenre: 'Genre',
    searchConsole: 'Console',
    searchSubmit: 'Search',
    searchReset: 'Reset',
    searchBack: '← Back to home',
    consoleAll: 'All consoles',
    advancedSearchEmpty: 'Please fill in at least one field.',
    searchAria: 'Game search',
    searchStartAria: 'Start search',
    searchResults: 'Search results',
    searchLoading: 'Searching…',
    searchNoResults: 'No matching games found in the database.',
    searchPrevPage: 'Previous page',
    searchNextPage: 'Next page',
    searchPageStatus: 'Page {page} of {total}',
    backToSearch: '← Back to search',
    breadcrumbNav: 'Breadcrumb',
    breadcrumbHome: 'Home',
    moreFromCreator: 'More guides by {name}',
    moreFromCreators: 'More guides by these creators',
    similarGuides: 'Similar guides',
    homeKicker: 'TrophyBase · Your guide hub',
    homeTitle: 'Find your next platinum run',
    homeSub:
      'Curated rows — from Souls hardcore to family platinums. Pick the series that fits your play style.',
    watchlistTitle: 'Watchlist',
    watchlistCountOne: '1 game',
    watchlistCountMany: '{n} games',
    watchlistEmpty:
      'No games on your watchlist yet. Star games in the categories or on a game page.',
    creatorCredit:
      'This guide uses footage from the wonderful videos by {name}. If you enjoy {name}’s videos as much as we do, please consider subscribing. Every bit of support helps create even more great content!',
    creatorYoutube: 'YouTube',
    platinGuide: 'Platinum guide',
    gameOverview: 'Overview of the {title} platinum guide',
    trophiesTotal: 'Trophies total',
    trophiesMissable: 'Missable trophies',
    trophiesOnline: 'Online trophies',
    playtimeTitle: 'Playtime',
    playtimeStory: 'Main story only',
    playtimeComplete: 'Completionist',
    playtimeHours: '{n} h',
    serverDeadPlatinum: 'Because the servers have been shut down, the platinum can no longer be earned through regular play.',
  },
  es: {
    profile: 'Perfil',
    login: 'Iniciar sesión',
    logout: 'Cerrar sesión',
    admin: 'Admin',
    language: 'Idioma',
    guideLanguage: 'Idioma de la guía',
    guideLanguageHint: 'Sitio',
    guideLanguageReset: 'Predeterminado',
    impressum: 'Aviso legal',
    privacy: 'Privacidad (RGPD)',
    howTo: 'En resumen',
    howToLead: 'Unos pocos gestos que hacen las guías más rápidas.',
    howToSwipeTitle: 'Deslizar y flechas',
    howToSwipeBody:
      'En una guía, desliza a la izquierda para la siguiente sección y a la derecha para la anterior. En el teclado, las flechas derecha e izquierda hacen lo mismo.',
    howToCheckTitle: 'Marcar y ocultar',
    howToCheckBody:
      'Los trofeos y los pasos de la guía se pueden marcar. “Ocultar completados” limpia la lista. Mostrar y ocultar en la cabecera recupera los juegos que hayas guardado.',
    howToWatchTitle: 'Watchlist',
    howToWatchBody:
      'La estrella guarda el juego en este navegador. La lista está en la portada. No hace falta una cuenta.',
    howToLandscapeTitle: 'Horizontal',
    howToLandscapeBody:
      'Con un vídeo en vertical aparece un aviso para girar el teléfono. Los pasos y la imagen quedan entonces uno al lado del otro.',
    howToReportTitle: 'Informar de un error',
    howToReportBody:
      'Selecciona texto en la guía. Encima aparece “Informar de un error”. El aviso llega a la redacción, con el pasaje que marcaste.',
    hintSwipe: 'Desliza a izquierda o derecha para cambiar de sección.',
    hintWatchlist: 'La estrella añade el juego a la watchlist.',
    hintMore: 'Más',
    hintOk: 'OK',
    hintLandscape: 'Para la mejor experiencia con vídeo, gira el dispositivo.',
    fairUseNote:
      'Carátulas, logos y títulos se usan solo para identificar juegos en una base editorial. TrophyBase no está afiliado a los titulares.',
    consentTitle: 'Contenido externo',
    consentBody:
      'Sin medición de audiencia ni cookies de afiliados. Los vídeos de YouTube se cargan solo con tu consentimiento (cookies de Google). Las miniaturas vienen del CDN de imágenes de YouTube, sin reproductor.',
    consentAllowYoutube: 'Permitir YouTube',
    consentNecessary: 'Rechazar',
    consentYoutubeGate:
      'Miniatura sin reproductor. YouTube establece cookies de Google solo al cargar el vídeo.',
    consentYoutubeLoad: 'Cargar vídeo de YouTube',
    dbConnected: '¡Conectado correctamente!',
    dbFailed: 'Error',
    dbLabel: 'BD',
    backDashboard: '← Volver al panel',
    trophies: 'Trofeos',
    fullGameplay: 'Walkthrough',
    completion: 'Coleccionables',
    bosses: 'Jefes',
    hideCompleted: 'Ocultar completados',
    trophyChecklist: 'Lista de trofeos',
    hiddenTrophies: 'Trofeos ocultos',
    hiddenTrophiesShow: 'Mostrar',
    hiddenTrophiesHide: 'Ocultar',
    hiddenTrophiesAlways: 'Mostrar siempre',
    hiddenTrophyName: 'Trofeo oculto',
    overallProgress: 'Progreso total',
    releaseYear: 'Año de lanzamiento',
    watchlistAdd: 'A la watchlist',
    watchlistOn: 'En la watchlist',
    watchlistAdded: 'Añadido a la watchlist.',
    watchlistRemoved: 'Quitado de la watchlist.',
    watchlistAddTitle: 'Añadir a la watchlist',
    watchlistRemoveTitle: 'Quitar de la watchlist',
    watchlistFailed: 'No se ha podido actualizar la watchlist.',
    share: 'Compartir',
    shareCopied: 'Enlace copiado.',
    shareFailed: 'No se ha podido copiar el enlace.',
    guideNotFoundTitle: 'Guía no encontrada',
    guideNotFoundBody:
      'Ahora mismo no hay ningún juego detrás de este enlace. Puede estar obsoleto o la guía aún se está revisando.',
    guideTabs: 'Secciones de la guía',
    prevTab: 'Sección anterior',
    nextTab: 'Sección siguiente',
    guideLoading: 'Cargando datos de la guía…',
    loadingGuide: 'Cargando guía…',
    searchPlaceholder: 'Título, género o estudio…',
    advancedSearch: 'Búsqueda avanzada',
    advancedSearchHint:
      'Combina título, estudio, género y consola. Los campos vacíos se ignoran.',
    searchTitle: 'Título',
    searchDeveloper: 'Estudio',
    studioLabel: 'Estudio',
    publisherLabel: 'Publisher',
    searchGenre: 'Género',
    searchConsole: 'Consola',
    searchSubmit: 'Buscar',
    searchReset: 'Restablecer',
    searchBack: '← Volver al inicio',
    consoleAll: 'Todas las consolas',
    advancedSearchEmpty: 'Rellena al menos un campo.',
    searchAria: 'Búsqueda de juegos',
    searchStartAria: 'Iniciar búsqueda',
    searchResults: 'Resultados de búsqueda',
    searchLoading: 'Buscando…',
    searchNoResults: 'No hay juegos coincidentes en la base de datos.',
    searchPrevPage: 'Página anterior',
    searchNextPage: 'Página siguiente',
    searchPageStatus: 'Página {page} de {total}',
    backToSearch: '← Volver a la búsqueda',
    breadcrumbNav: 'Migas de pan',
    breadcrumbHome: 'Inicio',
    moreFromCreator: 'Más guías de {name}',
    moreFromCreators: 'Más guías de estos creadores',
    similarGuides: 'Guías similares',
    homeKicker: 'TrophyBase · Tu hub de guías',
    homeTitle: 'Encuentra tu próxima platino',
    homeSub:
      'Filas curadas — del hardcore Souls a platino familiar. Elige la saga que encaje contigo.',
    watchlistTitle: 'Watchlist',
    watchlistCountOne: '1 juego',
    watchlistCountMany: '{n} juegos',
    watchlistEmpty:
      'Todavía no hay juegos en tu watchlist. Márcalos con el ☆ en las categorías o en la ficha del juego.',
    creatorCredit:
      'Esta guía utiliza imágenes de los vídeos de {name}. Si te gustan tanto como a nosotros, suscríbete. Cada apoyo ayuda a crear aún más contenido.',
    creatorYoutube: 'YouTube',
    platinGuide: 'Guía de platino',
    gameOverview: 'Resumen de la guía de platino de {title}',
    trophiesTotal: 'Trofeos en total',
    trophiesMissable: 'Trofeos perdibles',
    trophiesOnline: 'Trofeos en línea',
    playtimeTitle: 'Duración',
    playtimeStory: 'Solo historia principal',
    playtimeComplete: 'Completista',
    playtimeHours: '{n} h',
    serverDeadPlatinum: 'Por el cierre de los servidores, el platino ya no se puede conseguir de forma normal.',
  },
};

export const LOCALE_META = {
  ja: { label: '日本語', flag: '🇯🇵', short: 'JA' },
  en: { label: 'English', flag: '🇬🇧', short: 'EN' },
  fr: { label: 'Français', flag: '🇫🇷', short: 'FR' },
  es: { label: 'Español', flag: '🇪🇸', short: 'ES' },
  de: { label: 'Deutsch', flag: '🇩🇪', short: 'DE' },
  it: { label: 'Italiano', flag: '🇮🇹', short: 'IT' },
  nl: { label: 'Nederlands', flag: '🇳🇱', short: 'NL' },
  pt: { label: 'Português', flag: '🇵🇹', short: 'PT' },
  ru: { label: 'Русский', flag: '🇷🇺', short: 'RU' },
  ko: { label: '한국어', flag: '🇰🇷', short: 'KO' },
  'zh-hant': { label: '繁體中文', flag: '🇹🇼', short: 'ZH' },
  'zh-hans': { label: '简体中文', flag: '🇨🇳', short: 'ZH' },
  fi: { label: 'Suomi', flag: '🇫🇮', short: 'FI' },
  sv: { label: 'Svenska', flag: '🇸🇪', short: 'SV' },
};

export function t(locale, key) {
  const loc = UI_STRINGS[locale] ? locale : 'de';
  return UI_STRINGS[loc][key] ?? UI_STRINGS.de[key] ?? UI_STRINGS.en?.[key] ?? key;
}

export function localeOptions(codes = SUPPORTED_LOCALES) {
  return codes
    .filter((code) => LOCALE_META[code])
    .map((code) => ({
      code,
      ...LOCALE_META[code],
    }));
}
