-- online_trophies_log: Globale Referenz – welche Trophäen Online-Spiel erfordern.
-- game_id → public.games.id (UUID)
-- trophy_id → game_achievements.platform_achievement_id
-- Für Migration: migrate_user_tables_to_game_uuid.sql

create table if not exists public.online_trophies_log (
  id bigint generated by default as identity primary key,
  game_id uuid not null references public.games (id) on delete cascade,
  trophy_id text not null,
  trophy_name text,
  trigger_keyword text,
  found_in text,
  timestamp timestamptz default now()
);

create index if not exists idx_online_trophies_log_game
  on public.online_trophies_log (game_id);

alter table public.online_trophies_log enable row level security;

drop policy if exists "online_trophies_log_select_all" on public.online_trophies_log;

create policy "online_trophies_log_select_all" on public.online_trophies_log
  for select to authenticated, anon
  using (true);
